config/routes.rb
Rails.application.routes.draw do
  get 'temp_recommender/new'
  get 'recommenders/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  get 'search' => 'songs#find'
  get 'survey' => 'temp_recommender#survey'
  get 'surveydata' =>'temp_recommender#agree', as: "agree_survey"
  get 'recommend_for' => 'temp_recommender#recommend_song'

  mount Sidekiq::Monitor::Engine => '/sidekiq'
  root 'pages#home' 
  get'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'contact' =>'pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations,only:[:edit]
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :songs

end

app/views/pages/about.html.erb
<% provide(:title,"About") %>
<h1>About This Application</h1>
<p>	
I am student in Nagaoka University of Technology(NUT).
This application is for my research in NUT.
</p>	
<p>
<h2>=============Testing with System ===================</h2>

I would like to request your cooperation for my research in Music Recommendation System based on Lyric Analysis and User Behaviour.
The following are some steps for my research evaluation, and I hope to receive your feedback for my system.

Step by Step Procedure for Music Recommendation System Evaluation
<p>	
1. Please register in  My Research Recommendation System (http://khinezarthwe.me/). If you already registered please log in the system.
</p>
<p>
2.After you register and log in, Please find and listen your favourite songs ( In song tab, you can see all our uploaded songs in system. You can also use search box in our system). If you don’t find your favourite songs, you can upload the songs in the system. 
</p>
<p>
3.Please listen your favourite songs  ( at least 10 songs ) to know your recommendation.
</p>
<p>
4.After doing this, Please click link from home tab “Please click me to know recommendation” and wait for 1 or 2 minutes.
</p>
<p>
5.When you got the result, Please click the link “After knowing the result Please answer a survey for us!”
We select some songs for you. These songs are recommended songs for you. We appreciate your feedback on our system. 
</p>
<p>
Thank you so much for spending your valuable time and hope you have a nice day.
</p>


<p>
Khine Zar Thwe(Ms)<br>
Master 2nd Year,Knowledge System Laboratory<br>
Management and Information System Engineering<br>
Nagaoka University of Technology
</p>
</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<%= link_to "Contact",contact_path %>
<p>
 <center> You can contact via email : koalakhine@gmail.com<br>
  github account:  https://github.com/khinezarthwe
  </center>
</p>

app/views/pages/help.html.erb
<% provide(:title,"Help") %>
<h1>Help</h1>
<center>
<p>Please register and log in for your private music recommendation</p>
To get help on this app, please contact me via my email.<br>
Implementation are following by the guide line of 
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>
</center>

app/views/pages/home.html.erb
<% provide(:title,"Home") %>

<% if logged_in? %>

<div class="row">
  <section class= "col-md-9">
  <section class="col-md-6">
    <section class = "user_info">
      <%= render 'shared/user_info'%>
    </section>
  </section>
    
    
  </section>
  <section class="col-md-3">
    <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#songFormModal">
      Add New Song
    </button>
    <section id="songFormModal" class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="gridSystemModalLabel">Add New Song</h4>
          </div>
          <div class="modal-body song_form">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <%= render 'shared/song_form' %> 
              </div>
            </div>   
          </div> 
        </div>
      </div>
    </section>
  </section>
</div>
<% if @song.present? then %>
<div class="row">
<%= render 'shared/error_messages',object: @song %>
</div>
<% end %>
<div class="row">
  <br>
</div>
<div class="row">
  <aside class="col-md-12">
  <%= render 'shared/search_form' %>
  </aside>
</div>
<div class="row">
  <aside class="col-md-12">
    <%= render 'shared/recommend_form' %>
  </aside>
</div>
<div class="row">
  <aside class="col-md-4">
    <ol id='recommend_result' class="songs">
    </ol>
  </aside>
  <aside class="col-md-4">
    <ol id='recommend_result2' class="songs">
    </ol>
  </aside>
  <aside class="col-md-4">
    <ol id='recommend_result3' class="songs">
    </ol>
  </aside>
</div>
<% else %>
<div class="center jumbotron">

<h1>Music Recommendation System</h1>
<p>
	This is the Home Page for My Music Recommendation System
</p>
<%= link_to "Sign up now!",signup_path, class: "btn btn-lg btn-info"%>
<div class="row">
  <div class="col-md-6">
  Search your favourite songs<br>
  You can search the song lyric in my system.<br>
  We can recommend for you!
  </div>
  <div class="col-md-6">
  You can see Popular song in our system.<br>
  We can recommend specific recommend for you.
  We hope you can satisfy our results.

  </div>
</div>
</div>
<% end %>


	