config/routes.rb
Rails.application.routes.draw do
  get 'temp_recommender/new'
  get 'recommenders/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  get 'search' => 'songs#find'
  get 'survey' => 'temp_recommender#survey'
  get 'surveydata' =>'temp_recommender#agree', as: "agree_survey"
  get 'recommend_for' => 'temp_recommender#recommend_song'

  mount Sidekiq::Monitor::Engine => '/sidekiq'
  root 'pages#home' 
  get'help' => 'pages#help'
  get 'about' => 'pages#about'
  get 'contact' =>'pages#contact'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations,only:[:edit]
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :songs

end

app/models/temp_recommender.rb
class TempRecommender < ActiveRecord::Base
	
end

app/controllers/temp_recommender_controller.rb
class TempRecommenderController < ApplicationController
  
  def new
  end

  def agree
    @song_id = params[:song_id]
    @user_id = params[:user_id]
    @agreed = params[:agreed]
    @survey_action = SurveyAction.new
    @survey_action.user_id  = @user_id
    @survey_action.song_id  = @song_id
    @survey_action.agreed   = @agreed
    survey_song_topic = TempRecommender.select('song_id').where(:user_id=>current_user.id).pluck(:song_id)
    @survey_song_topic_hash = Hash["topic" => survey_song_topic]
    @survey_action.topic    = @survey_song_topic_hash["topic"].include?@song_id.to_i
    
    survey_song_genre = GenreBasedRecommendation.select('song_id').where(:user_id=>current_user.id).pluck(:song_id)
    @survey_song_genre_hash = Hash["genre" => survey_song_genre]
    @survey_action.genre    = @survey_song_genre_hash["genre"].include?@song_id.to_i

    survey_song_ncf = NcFrecommendation.select('song_id').where(:user_id=>current_user.id).pluck(:song_id)
    @survey_song_ncf_hash = Hash["ncf" => survey_song_ncf]
    @survey_action.ncf      = @survey_song_ncf_hash["ncf"].include?@song_id.to_i


    @survey_action.save!
    respond_to do|format|
      format.html
      format.js
    end
  end

  def survey
    survey_song = surveyselectdata
    @survey_song_for_eva = Song.where(:id=>survey_song).pluck(:video_link,:id)
    respond_to do|format|
      format.html
      format.js 
    end
  end

  def recommend_song
    arr_songs = []
    genre_songs = []
    nf_songs = []
    #a = RecommendWorker.new
    #a.perform(current_user.id)
    a = TopicModelWorker.new
    a.perform(current_user.id)
    #TopicModelWorker.perform_async(current_user.id)
    b = GenreBasedRecommendWorker.new
    b.perform(current_user.id)
    #GenreBasedRecommendWorker.perform_async(current_user.id)
    c = Normalcf.new
    c.perform(current_user.id)
    # Adding normal collaborative filtering result
    temp_recommend_song = TempRecommender.where(:user_id=>current_user.id)
    if temp_recommend_song.nil?
      @recommend_song = []
    else
      temp_recommend_song.each do |song|
        arr_songs << song.song_id
      end
      @recommend_song = Song.where(:id=>arr_songs)
    end

    genre_recommend_song = GenreBasedRecommendation.where(:user_id=>current_user.id)

    if genre_recommend_song.nil?
      @genre_recommend_song = []
    else
      genre_recommend_song.each do |song|
        genre_songs << song.song_id
      end
      @genre_recommend_song = Song.where(:id=>genre_songs)
    end
    nf_recommend_song = NcFrecommendation.where(:user_id=>current_user.id)
    if nf_recommend_song.nil?
      @nf_recommend_song = []
    else
      nf_recommend_song.each do |song|
        nf_songs << song.song_id
      end
      @nf_recommend_song = Song.where(:id=>nf_songs)
    end
    respond_to do|format|
      format.html
      format.js
    end
  end

  def surveyselectdata
    survey_song_topic = survey_song_genre = survey_song_ncf = []
    #@survey_song_topic_hash = @survey_song_genre_hash = @survey_song_ncf_hash = {}

    survey_song_topic = TempRecommender.select('song_id').where(:user_id=>current_user.id).pluck(:song_id)
    #@survey_song_topic_hash = Hash["topic" => survey_song_topic]
    
    survey_song_genre = GenreBasedRecommendation.select('song_id').where(:user_id=>current_user.id).pluck(:song_id)
    #@survey_song_genre_hash = Hash["genre" => survey_song_genre]

    survey_song_ncf = NcFrecommendation.select('song_id').where(:user_id=>current_user.id).pluck(:song_id)
    #@survey_song_ncf_hash = Hash["ncf" => survey_song_ncf]

    @survey_song = survey_song_topic+survey_song_genre+survey_song_ncf
  end 
end

app/helpers/temp_recommender_helper.rb
module TempRecommenderHelper
end

app/views/temp_recommender/agree.js.erb
//alert('<%= "#{@song_id}: #{@user_id}" %>');
$('#video_show').remove();

app/views/temp_recommender/recommend_song.js.erb
$('#recommend_result').html("<h4>Recommended Song!</h4><%= j (render @recommend_song) %>");
$('#recommend_result').slideDown(500);
$('#recommend_result2').html("<h4>Recommended Song!</h4><%= j (render @genre_recommend_song) %>");
$('#recommend_result2').slideDown(500);
$('#recommend_result3').html("<h4>Recommended Song!</h4><%= j (render @nf_recommend_song) %>");
$('#recommend_result3').slideDown(500);

app/views/temp_recommender/survey.html.erb
<% provide(:title, "Survey for you")%>

<h3>Dear <%= current_user.name %>,
<br></h3>
 <h4>We select total <%= @survey_song_for_eva.count %> songs for you. Please listen our selected songs and please click agree or disagree with your opinion.
 </h4>

<br>
<br>
<% @survey_song_for_eva.each do |video,song_id| %>
<div id="video_show">
<p> <%= raw(youtube_embed_small(video)) %> <br>
<button type="button" class="btn btn-default"> <%= link_to "Like", agree_survey_path(user_id: current_user.id, song_id: song_id, agreed: true),remote: true %> </button>
<button type="button" class="btn btn-default"> <%= link_to "DisLike",agree_survey_path(user_id: current_user.id, song_id: song_id, agreed: false), remote: true %> </button>
</p>
</div>

<% end %>
<div class="row">
<script>(function(e,t,n,c){var s,o,a;e.SMCX=e.SMCX||[],t.getElementById(c)||(s=t.getElementsByTagName(n),o=s[s.length-1],a=t.createElement(n),a.type="text/javascript",a.async=!0,a.id=c,a.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/kgsXbcEnbup2T4qWpLAFvKFFOMR2h8FFdeWea_2FP6acf_2BV61fHCa3_2BLCA9rMWGWnS.js"].join(""),o.parentNode.insertBefore(a,o))})(window,document,"script","smcx-sdk");</script><a style="font: 12px Helvetica, sans-serif; color: #999; text-decoration: none;" href=https://www.surveymonkey.com/mp/customer-satisfaction-surveys/> Create your own user feedback survey </a>
</div>
<br>
Thanks a lot for your cooperation. 
<br>
Best Regards,
<br>
Khine Zar

app/views/temp_recommender/survey.js.erb
$('#video_show').remove();